#!/usr/bin/env python 

import urllib2
import sys

URL = "http://paste.famp.co"

if sys.stdin.isatty():
    filecontents = open(sys.argv[1], 'r')
    try:
        data = "".join(filecontents.readlines()).strip()
    finally:
        filecontents.close()
else:
    data = "".join(sys.stdin.readlines()).strip()

req = urllib2.Request(URL + "/documents", data)
response = urllib2.urlopen(req)
responsedata = response.read()
responseeval = eval(responsedata)
sys.stdout.write("%s/%s\n" % (URL, responseeval['key']))
